feat: add i2b2 mapping
DataTools4Heart/data-ingestion-suite pull request #19
Opened 2024-10-24 08:19 UTC by oburakcinar

2024-10-31 10:38 UTC, dogukan10 requested changes

2024-11-07 07:58 UTC, YemreGurses requested changes

2024-11-07 07:58 UTC, YemreGurses commented on mappings/i2b2/lab-results-mapping.json
> +            "code" : "{{%labCodeValue}}",
Some codes does not exists in our valueset: https://github.com/DataTools4Heart/common-data-model/blob/29b62f72230c66bd48dd153d8ffaa4ba7ea37ee2/valuesets/lab-result.json

E.g.
![image](https://github.com/user-attachments/assets/5eea931e-f4b9-4ac5-9deb-14eeb5fa3e8b)
Can you check those labs if it is possible to convert or perform unit conversion or discard them?

2024-11-07 07:58 UTC, YemreGurses commented on terminology-systems/DT4HTerminologyService/stringToSnomed.csv
> +"source_system","source_code","target_system","target_code","target_display"
Let's give a meaningful name to this file. e.g. LabResults-Ib2bToSnomed

2024-11-26 07:04 UTC, YemreGurses requested changes

2024-11-26 07:07 UTC, YemreGurses requested changes
Have you run these mappings with complete dataset from https://drive.google.com/drive/folders/11a6Yr-T9DSj0KsJ9XP4HQwgbwTfORRQu ?

2024-12-09 08:27 UTC, merged